### ISSUE TITLE
Does not integrate well with dark panels

### ISSUE THREAD

**Issue by Sidnioulz** [andrzej-r/xfce4-pulseaudio-plugin#2]
Hey André,

On a dark panel (using the Greybird theme), the background of the plugin is light grey, making it hard to see -- because I use a dark-panel icon theme that matches my dark panel. Could I suggest you don't use a default background color at all?

Thanks.

**Comment by andrzej-r** [comment]
The plugin uses gtk3 so it requires the theme to support it. Greybird works just fine here, but as far as I remember old versions of this theme did not have dark color theme for gtk3 panel widgets. Try updating Greybird.

In retrospect, I should have used gtk2 for this plugin but at the time I started working on it there was a plan that a new release of xfce4-panel would support gtk3.

**Comment by Sidnioulz** [comment]
I see!

Be aware that GtkPlug/GtkSocket will be deprecated by Gtk3 at some point as they are not implemented in Gtk3's Wayland backend.

**Comment by andrzej-r** [comment]
Yes, I am aware of that. Frankly speaking no one is considering Wayland support at this stage and the use of XEmbed in panel plugins is the least concern.
