### ISSUE TITLE
Not compiling :(

### ISSUE THREAD

**Issue by sixtyfive** [andrzej-r/xfce4-pulseaudio-plugin#5]
Hi! You seem to have a file missing - or is it me who is missing something?

    make[1]: Entering directory '/home/jrs/Builds/XFCE/xfce4-pulseaudio-plugin/panel-plugin'
      CC       libpulseaudio_plugin_la-pulseaudio-dialog.lo
    pulseaudio-dialog.c:42:34: fatal error: pulseaudio-dialog_ui.h: No such file or directory

**Comment by andrzej-r** [comment]
Use --enable-maintainer-mode when running ./autogen.sh. This will not be required in a released version (when building from a tarball, not git).
