### ISSUE TITLE
PulseAudio Plugin not respecting gtk/panel theme.

### ISSUE THREAD

**Issue by korrode** [andrzej-r/xfce4-pulseaudio-plugin#6]
The panel plugin isn't respecting the theme properly.

In this screenshot i placed the old Audio Mixer plugin to the right of the PulseAudio plugin, to show how it should look.
![xfce4-pulseaudio-plugin_colour](https://cloud.githubusercontent.com/assets/4949717/6683926/49dcf6e0-cce0-11e4-9b31-6abb13f63661.png)

**Comment by ochosi** [comment]
It does respect the theme, however your theme needs to have Gtk3 support. Look at Greybird for hints: https://github.com/shimmerproject/Greybird/blob/master/gtk-3.0/apps/xfce.css#L44

**Comment by korrode** [comment]
Ah, thanks. Indeed my theme is simply Adwaita with GTK2 stuff added for a dark Xfce panel. I'll add customisations for GTK3 too.
